// ════════════════════════════════════════════════════════════════════════════
// /robots.txt — generated by Next.js (App Router convention).
//
// The site had NO robots.txt at all, so crawlers were free to index the private
// surface: the client portal, the admin screens and every API route. Those must be
// excluded — not because robots.txt is a security control (it is not; access is
// enforced by RLS and server-side authorization), but because indexing them leaks
// structure, wastes crawl budget, and surfaces login-walled URLs in search results.
//
// Kept deliberately small: allow the public marketing pages, disallow everything
// that requires a session, and point at the sitemap.
// ════════════════════════════════════════════════════════════════════════════
import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",            // every route handler — never useful to a crawler
          "/client-portal/",  // the whole authenticated portal
          "/admin/",          // admin screens
          "/quick-access/",   // token/shortcut entry surface
          // Secure document grants. The token lives in the URL fragment, which a
          // crawler never sends anywhere, so there is nothing here to index —
          // only an empty shell. Disallowed so the page never appears in search
          // results as a "Kian document portal" and invites token guessing.
          "/secure-document",
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
