// ════════════════════════════════════════════════════════════════════════════
// /sitemap.xml — generated by Next.js (App Router convention).
//
// The site had no sitemap. This lists ONLY the public marketing pages; everything
// behind a login (the client portal), the admin screens and the token entry surface
// are deliberately absent — they are also disallowed in robots.ts.
//
// Static list on purpose: these routes are statically known, so there is no query and
// no chance of leaking a private URL into a public file.
// ════════════════════════════════════════════════════════════════════════════
import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site";

/** Public routes only. changeFrequency/priority are hints, not guarantees. */
const PUBLIC_ROUTES: { path: string; changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"]; priority: number }[] = [
  { path: "/",                changeFrequency: "weekly",  priority: 1.0 },
  { path: "/quote-request",   changeFrequency: "monthly", priority: 0.9 },
  { path: "/book-meeting",    changeFrequency: "monthly", priority: 0.8 },
  { path: "/opportunities",   changeFrequency: "weekly",  priority: 0.7 },
  { path: "/upload-files",    changeFrequency: "yearly",  priority: 0.4 },
  { path: "/privacy-policy",  changeFrequency: "yearly",  priority: 0.3 },
  { path: "/terms",           changeFrequency: "yearly",  priority: 0.3 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  return PUBLIC_ROUTES.map((r) => ({
    url: `${SITE_URL}${r.path}`,
    lastModified,
    changeFrequency: r.changeFrequency,
    priority: r.priority,
  }));
}
