// ════════════════════════════════════════════════════════════════════════════
// /sitemap.xml — generated by Next.js (App Router convention).
//
// The site had no sitemap. This lists ONLY the public marketing pages; everything
// behind a login (the client portal), the admin screens and the token entry surface
// are deliberately absent — they are also disallowed in robots.ts.
//
// Static list on purpose: these routes are statically known, so there is no query and
// no chance of leaking a private URL into a public file.
//
// ── ONE deliberate exception: published case studies ────────────────────────
// cs_public_slugs() returns slugs ONLY for studies that are published, past their
// publish_at, not archived, permission-cleared and behind the owner's public switch —
// the same gate the public page uses. It returns no other column: no id, no storage
// path, no draft, no preview token (there is no such token in this system at all).
// If the migration is unapplied, the switch is off, or the network fails, the helper
// returns [] and this file degrades to exactly the static list it was before.
// A private URL cannot reach this file, because a non-public study has no slug here.
// ════════════════════════════════════════════════════════════════════════════
import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site";
import { publicCaseStudySlugs } from "@/lib/server/publicCaseStudies";

/** Public routes only. changeFrequency/priority are hints, not guarantees. */
const PUBLIC_ROUTES: { path: string; changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"]; priority: number }[] = [
  { path: "/",                changeFrequency: "weekly",  priority: 1.0 },
  { path: "/quote-request",   changeFrequency: "monthly", priority: 0.9 },
  { path: "/book-meeting",    changeFrequency: "monthly", priority: 0.8 },
  { path: "/opportunities",   changeFrequency: "weekly",  priority: 0.7 },
  { path: "/upload-files",    changeFrequency: "yearly",  priority: 0.4 },
  { path: "/privacy-policy",  changeFrequency: "yearly",  priority: 0.3 },
  { path: "/terms",           changeFrequency: "yearly",  priority: 0.3 },
];

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const lastModified = new Date();
  const base: MetadataRoute.Sitemap = PUBLIC_ROUTES.map((r) => ({
    url: `${SITE_URL}${r.path}`,
    lastModified,
    changeFrequency: r.changeFrequency,
    priority: r.priority,
  }));

  // Never throws: publicCaseStudySlugs() swallows every failure and returns [].
  const studies = await publicCaseStudySlugs();
  if (studies.length === 0) return base;   // feature off / unapplied / nothing published

  return [
    ...base,
    { url: `${SITE_URL}/case-studies`, lastModified, changeFrequency: "weekly", priority: 0.8 },
    ...studies.map((s) => {
      // A malformed date must not throw during sitemap generation — fall back.
      const d = s.updated_at ? new Date(s.updated_at) : null;
      return {
        url: `${SITE_URL}/case-studies/${s.slug}`,
        lastModified: d && !Number.isNaN(d.getTime()) ? d : lastModified,
        changeFrequency: "monthly" as const,
        priority: 0.6,
      };
    }),
  ];
}
