// Auto-generated client roster.
// Each client has a `slug` — place logo at /public/clients/{slug}.png and it will display.
// If logo missing, the name is shown elegantly.

export type Client = { slug: string; en: string; ar: string };

export const CLIENTS: Client[] = [
  { slug: "esports-world-cup", en: "Esports World Cup", ar: "كأس العالم للرياضات الإلكترونية" },
  { slug: "mokbel-al-khalaf", en: "Mokbel Al Khalaf Sons Co.", ar: "شركة أبناء مقبل الخلف التجارية" },
  { slug: "bateel", en: "Bateel International", ar: "بتيل" },
  { slug: "abunayyan", en: "Abunayyan Holding", ar: "أبو نيان القابضة" },
  { slug: "ardara", en: "Ardara", ar: "أردارا" },
  { slug: "alshaya", en: "Alshaya International Co.", ar: "الشايع" },
  { slug: "bsf", en: "BSF", ar: "البنك السعودي الفرنسي" },
  { slug: "pepsico", en: "PepsiCo", ar: "بيبسيكو" },
  { slug: "naif-arab-univ", en: "Naif Arab University for Security Sciences", ar: "جامعة نايف العربية للعلوم الأمنية" },
  { slug: "olayan", en: "Olayan Financing Company", ar: "شركة العليان المالية" },
  { slug: "baja", en: "Baja Food Industries", ar: "بهجة للصناعات الغذائية" },
  { slug: "egis", en: "Egis Saudi Arabia", ar: "إيجيس السعودية" },
  { slug: "alayuni", en: "Al Ayuni Investment & Contracting", ar: "العيوني للاستثمار والمقاولات" },
  { slug: "schs", en: "Saudi Commission for Health Specialties", ar: "الهيئة السعودية للتخصصات الصحية" },
  { slug: "ceer", en: "CEER Motors", ar: "سير للسيارات" },
  { slug: "dan-company", en: "DAN Company", ar: "شركة دان" },
  { slug: "rolls-royce", en: "Rolls-Royce Saudi Arabia", ar: "رولز رويس السعودية" },
  { slug: "talemia", en: "Talemia", ar: "تعلمية" },
  { slug: "tatweer-buildings", en: "Tatweer for Buildings", ar: "تطوير للمباني" },
  { slug: "rafid", en: "Rafid – Tatweer Transport", ar: "رافد لخدمات النقل" },
  { slug: "tetco", en: "TETCO", ar: "تيتكو" },
  { slug: "riyadh-air", en: "Riyadh Air", ar: "طيران الرياض" },
  { slug: "henkel", en: "Henkel Arabia", ar: "هنكل العربية" },
  { slug: "united-seqa", en: "United Seqa Group", ar: "مجموعة السقا المتحدة" },
  { slug: "hevolution", en: "Hevolution Foundation", ar: "مؤسسة هيفولوشن" },
  { slug: "rcjy", en: "Royal Commission for Jubail & Yanbu", ar: "الهيئة الملكية للجبيل وينبع" },
  { slug: "aramco", en: "Aramco", ar: "أرامكو السعودية" },
  { slug: "sec", en: "Saudi Electricity Company", ar: "الشركة السعودية للكهرباء" },
  { slug: "maaden", en: "Maaden", ar: "معادن" },
  { slug: "ithra", en: "Ithra", ar: "إثراء" },
  { slug: "bupa", en: "Bupa Arabia", ar: "بوبا العربية" },
  { slug: "saudi-film-commission", en: "Saudi Film Commission", ar: "هيئة الأفلام السعودية" },
  { slug: "saudi-film-festival", en: "Saudi Film Festival", ar: "مهرجان أفلام السعودية" },
  { slug: "cinema-association", en: "Cinema Association", ar: "جمعية السينما" },
  { slug: "kfupm", en: "KFUPM", ar: "جامعة الملك فهد للبترول والمعادن" },
  { slug: "hrsd", en: "Ministry of HR & Social Dev.", ar: "وزارة الموارد البشرية" },
  { slug: "eastern-municipality", en: "Eastern Province Municipality", ar: "أمانة المنطقة الشرقية" },
  { slug: "traffic-dept", en: "General Directorate of Traffic", ar: "الإدارة العامة للمرور" },
  { slug: "ashi-bushnaq", en: "Ashi & Bushnaq", ar: "عاشي وبوشناق" },
  { slug: "saudi-diesel", en: "Saudi Diesel Equipment", ar: "الشركة السعودية للديزل" },
  { slug: "jac-motors", en: "JAC Motors", ar: "جاك موتورز" },
  { slug: "arasco", en: "ARASCO", ar: "أراسكو" },
  { slug: "gal", en: "GAL", ar: "GAL" },
  { slug: "nadsco", en: "NADSCO", ar: "ندسكو" },
  { slug: "delta", en: "Delta", ar: "دلتا" },
  { slug: "golden-ideas", en: "Golden Ideas", ar: "أفكار ذهبية" },
  { slug: "admex", en: "Admex", ar: "أدمكس" },
  { slug: "alotaishan", en: "Al Otaishan Holding", ar: "العتيشان القابضة" },
  { slug: "rawana", en: "Rawana", ar: "روانة" },
  { slug: "aldarah", en: "Aldarah", ar: "الدارة" },
  { slug: "adl", en: "Adl Real Estate", ar: "عدل العقارية" },
  { slug: "reviva", en: "Reviva", ar: "ريفايفا" },
  { slug: "khobar-cup", en: "Khobar Cup", ar: "كأس الخبر" },
  { slug: "dammam-equestrian", en: "Dammam Equestrian Field", ar: "ميدان الدمام للفروسية" },
  { slug: "global-city-dammam", en: "Global City Dammam", ar: "مدينة الدمام العالمية" },
  { slug: "wonder-hills", en: "Wonder Hills Jubail", ar: "وندر هيلز الجبيل" },
  { slug: "omar-buffet", en: "Omar Buffet", ar: "بوفيه عمر" },
  { slug: "asyakh", en: "Asyakh Restaurant", ar: "مطعم أسياخ" },
  { slug: "bcare", en: "B Care Clinics", ar: "عيادات بي كير" },
  { slug: "zara-clinics", en: "Zara Clinics", ar: "عيادات زارا" },
  { slug: "sham-clinics", en: "Sham Clinics", ar: "عيادات شام" },
  { slug: "alhekail", en: "Al Hekail Medical", ar: "مجمع الحقيل الطبي" },
  { slug: "alataa", en: "Al Ataa Society Qatif", ar: "جمعية العطاء بالقطيف" },
  { slug: "alyamama", en: "Al Yamama Society", ar: "جمعية اليمامة" },
  { slug: "albir", en: "Al Bir Society", ar: "جمعية البر" },
];